# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b9bd26856d6f8c7fcd7677bc33564afadc0ce22ff1d069912600623383d6dcbc34e3374cd928e5e77c69de88cdb8f4b72537e0dd5a9327d9dd9f493553f146b

test:
  secret_key_base: f758b536be57d8890a01b46844a6ec73e6a44e98d7a041fe26f48f6fc4aee5ebcf38c6f9e837ad7a7eb564a3048667596ae24dd52098f825f090686ac8275dba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
